# qpOASES 3.2.0, upstream commit 268b2f2659604df27c82aa6e32aeddb8c1d5cc7f.
set(QPOASES_SOURCE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/qpOASES")
file(GLOB QPOASES_SOURCES CONFIGURE_DEPENDS "${QPOASES_SOURCE_DIR}/src/*.cpp")
add_library(qpOASES SHARED ${QPOASES_SOURCES})
target_compile_definitions(qpOASES PRIVATE __NO_COPYRIGHT__ LINUX)
target_include_directories(qpOASES PUBLIC
        $<BUILD_INTERFACE:${QPOASES_SOURCE_DIR}/include>
        $<INSTALL_INTERFACE:include>)
set_target_properties(qpOASES PROPERTIES SOVERSION 3.2)

install(FILES "${QPOASES_SOURCE_DIR}/include/qpOASES.hpp"
        DESTINATION ${CATKIN_GLOBAL_INCLUDE_DESTINATION})
install(DIRECTORY "${QPOASES_SOURCE_DIR}/include/qpOASES"
        DESTINATION ${CATKIN_GLOBAL_INCLUDE_DESTINATION})
install(FILES "${QPOASES_SOURCE_DIR}/LICENSE.txt" "${QPOASES_SOURCE_DIR}/AUTHORS.txt"
        DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/third_party/qpOASES)
